apiVersion: v1
kind: Pod
metadata:
  name: jms-solace-pod
  labels:
    app: jms-solace
spec:
  containers:
    - name: jms-solace
      image: solace/solace-pubsub-standard:latest
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      ports:
        - containerPort: 8080
        - containerPort: 55555
        - containerPort: 8008
        - containerPort: 1883
        - containerPort: 5672
        - containerPort: 9000
        - containerPort: 2222
      env:
        - name: shm_size
          value: "2g"
        - name: username_admin_globalaccesslevel
          value: "admin"
        - name: username_admin_password
          value: "admin"
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi