apiVersion: v1
kind: Pod
metadata:
  name: jms-subscriber-pod-activemq
  labels:
    app: jms-subscriber-activemq
spec:
  containers:
    - name: jms-subscriber-pod
      image: sudhirreddy781/jms-sub-activemq:latest
      ports:
        - containerPort: 8089
      envFrom:
        - configMapRef:
            name: jms-subscriber-activemq-config-map