apiVersion: v1
kind: Service
metadata:
  name: activemq-service
spec:
  selector:
    app: my-activemq-pod
  ports:
    - port: 8161
      targetPort: 8161
      protocol: TCP
      nodePort: 30090
      name: dashboard
    - port: 61616
      targetPort: 61616
      protocol: TCP
      nodePort: 30091
      name: openwire
    - port: 5672
      targetPort: 5672
      protocol: TCP
      nodePort: 30092
      name: amqp
    - port: 61613
      targetPort: 61613
      protocol: TCP
      nodePort: 30093
      name: stomp
    - port: 1883
      targetPort: 1883
      protocol: TCP
      nodePort: 30094
      name: mqtt
  type: NodePort