apiVersion: v1
kind: Service
metadata:
  name: jms-publisher-service
spec:
  selector:
    app: jms-publisher
  ports:
    - port: 8080
      targetPort: 8088
      protocol: TCP
      nodePort: 30081
      name: publisher-port
  type: NodePort