apiVersion: v1
kind: Service
metadata:
  name: jms-subscriber-activemq-service
spec:
  selector:
    app: jms-subscriber-activemq
  ports:
    - port: 8080
      targetPort: 8089
      protocol: TCP
      nodePort: 30172
      name: subscriber-port
  type: NodePort