apiVersion: v1
kind: Service
metadata:
  name: jms-subscriber-service-with-configmap
spec:
  selector:
    app: jms-subscriber-with-configmap
  ports:
    - port: 8080
      targetPort: 8089
      protocol: TCP
      nodePort: 30072
      name: subscriber-port
  type: NodePort