apiVersion: v1
kind: ConfigMap
metadata:
  name: jms-subscriber-activemq-config-map
data:
  solace.host: "tcp://192.168.49.2:30091"
  solace.vpnName: "default"
  solace.userName: "admin"
  solace.pwd: "admin"
  solace.topic: "Topic1"